"""Faithful SimpleMem driver.

Wraps `competitors/simplemem/simplemem/main.py:SimpleMemSystem`. SimpleMem's
default embedder (Qwen3-Embedding-0.6B) is not locally available; their
`utils/embedding.py` falls back to `sentence-transformers/all-MiniLM-L6-v2`
when the primary model fails to load, so we run with the fallback to avoid
a 1.2GB download on a tight-disk machine.

Session-id traceback
--------------------
SimpleMem's `add_dialogue(speaker, content, timestamp)` stores `timestamp`
on the resulting MemoryEntry. We encode each input session as a unique
ISO date `2025-01-DDTHH:MM:SS` where DD = (1 + session_idx mod 28). On
retrieval we read entry.timestamp and parse DD back to session_idx.

Budget enforcement: post_truncate by entry timestamp recency / topic.
"""
from __future__ import annotations

import os
import shutil
import sys
import tempfile
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SM_PKG = ROOT / "competitors" / "simplemem" / "simplemem"
sys.path.insert(0, str(SM_PKG))
sys.path.insert(0, str(ROOT))
sys.path.insert(0, "/home/workspace/lww/project0412/projects/dataset")

from competitors._common.protocol import (  # noqa: E402
    ConsolidatedBuffer, Item, post_truncate_to_budget,
)

BUDGET_INDEPENDENT_CONSOLIDATE = True


def _ensure_config(llm_model: str = "deepseek-v3.2") -> Path:
    """Create a config.py inside SM_PKG if absent (uses MAAS routing)."""
    cfg_path = SM_PKG / "config.py"
    if cfg_path.exists():
        return cfg_path
    from api import _inject_api_key_from_file  # type: ignore  # noqa: WPS433
    _inject_api_key_from_file()
    api_key = os.environ.get("MAAS_API_KEY", "")
    cfg_path.write_text(
        f"""# auto-generated by BASC competitor wrapper
OPENAI_API_KEY = {api_key!r}
OPENAI_BASE_URL = "https://api.modelarts-maas.com/openai/v1"
LLM_MODEL = {llm_model!r}
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_DIMENSION = 384
EMBEDDING_CONTEXT_LENGTH = 512
ENABLE_THINKING = False
USE_STREAMING = False
ENABLE_PLANNING = True
ENABLE_REFLECTION = False
MAX_REFLECTION_ROUNDS = 0
ENABLE_PARALLEL_PROCESSING = False
MAX_PARALLEL_WORKERS = 1
ENABLE_PARALLEL_RETRIEVAL = False
MAX_RETRIEVAL_WORKERS = 1
JSON_FORMAT = False
"""
    )
    return cfg_path


def _split_dialogue(text: str) -> list[tuple[str, str]]:
    """Return list of (speaker, content) pairs from a session text blob."""
    out: list[tuple[str, str]] = []
    cur_speaker: str | None = None
    cur_buf: list[str] = []
    for line in text.splitlines():
        l = line.strip()
        if l.startswith("user:"):
            if cur_speaker:
                out.append((cur_speaker, " ".join(cur_buf).strip()))
            cur_speaker = "user"; cur_buf = [l[5:].strip()]
        elif l.startswith("assistant:"):
            if cur_speaker:
                out.append((cur_speaker, " ".join(cur_buf).strip()))
            cur_speaker = "assistant"; cur_buf = [l[10:].strip()]
        elif l.startswith("speaker_a:"):
            if cur_speaker:
                out.append((cur_speaker, " ".join(cur_buf).strip()))
            cur_speaker = "speaker_a"; cur_buf = [l[10:].strip()]
        elif l.startswith("speaker_b:"):
            if cur_speaker:
                out.append((cur_speaker, " ".join(cur_buf).strip()))
            cur_speaker = "speaker_b"; cur_buf = [l[10:].strip()]
        else:
            cur_buf.append(l)
    if cur_speaker:
        out.append((cur_speaker, " ".join(cur_buf).strip()))
    return out or [("user", text[:8000])]


def _ts_for_idx(i: int) -> str:
    """Encode session_idx into an ISO-8601 date that survives normalisation."""
    day = 1 + (i % 28)
    return f"2025-01-{day:02d}T00:00:00"


def _idx_from_ts(ts: str) -> int | None:
    if not isinstance(ts, str) or not ts.startswith("2025-01-"):
        return None
    try:
        day = int(ts[8:10])
    except ValueError:
        return None
    return day - 1 if 1 <= day <= 28 else None


def consolidate(memory: list[Item], *, budget_tokens: int,
                reader_model: str | None = None,
                seed: int = 7,
                llm_model: str = "deepseek-v3.2") -> ConsolidatedBuffer:
    del reader_model
    _ensure_config(llm_model=llm_model)

    tmp = Path(tempfile.mkdtemp(prefix=f"simplemem_basc_{seed}_"))
    db_path = tmp / "lancedb"
    db_path.mkdir(parents=True, exist_ok=True)

    try:
        from main import SimpleMemSystem  # noqa: WPS433
    except Exception as e:
        return ConsolidatedBuffer(
            retained_text=["" for _ in memory],
            retrievable_mask=[False for _ in memory],
            total_tokens=0,
            budget_enforcement="import-failed",
            notes=dict(error=str(e)[:200]),
        )

    try:
        sys_ = SimpleMemSystem(
            api_key=os.environ.get("MAAS_API_KEY", ""),
            model=llm_model,
            base_url="https://api.modelarts-maas.com/openai/v1",
            db_path=str(db_path),
            table_name=f"basc_{seed}",
            clear_db=True,
            enable_planning=False,
            enable_reflection=False,
            enable_parallel_processing=False,
        )
    except Exception as e:
        shutil.rmtree(tmp, ignore_errors=True)
        return ConsolidatedBuffer(
            retained_text=["" for _ in memory],
            retrievable_mask=[False for _ in memory],
            total_tokens=0,
            budget_enforcement="instantiation-failed",
            notes=dict(error=str(e)[:200]),
        )

    # Ingest each session's turns with our timestamp-encoded session_idx.
    for i, it in enumerate(memory):
        ts = _ts_for_idx(i)
        for spk, content in _split_dialogue(it.text):
            if not content:
                continue
            try:
                sys_.add_dialogue(speaker=spk, content=content[:4000], timestamp=ts)
            except Exception:
                pass

    # Walk vector store entries → recover session_idx provenance.
    n = len(memory)
    retained_per_idx: dict[int, list[str]] = {}
    importance: list[float] = [0.0] * n
    try:
        # SimpleMem's vector_store exposes a list of MemoryEntry-like dicts.
        all_entries = sys_.vector_store.get_all() if hasattr(sys_.vector_store, "get_all") else []
        for ent in all_entries:
            ts = ent.get("timestamp") if isinstance(ent, dict) else getattr(ent, "timestamp", None)
            idx = _idx_from_ts(ts)
            if idx is None or idx >= n:
                continue
            txt = ent.get("lossless_restatement") if isinstance(ent, dict) else getattr(ent, "lossless_restatement", "")
            if txt:
                retained_per_idx.setdefault(idx, []).append(txt)
                importance[idx] = max(importance[idx], 1.0)
    except Exception:
        pass

    retained_text = [" ".join(retained_per_idx.get(i, [])) for i in range(n)]
    n_kept_tokens = [len(t.split()) for t in retained_text]
    retrievable_mask = [bool(t.strip()) for t in retained_text]
    cur = sum(n_kept_tokens)
    enforcement = "native"
    if cur > budget_tokens:
        retained_text, retrievable_mask, cur = post_truncate_to_budget(
            retained_text, retrievable_mask, n_kept_tokens, importance,
            budget_tokens,
        )
        enforcement = "post-truncate"

    shutil.rmtree(tmp, ignore_errors=True)
    return ConsolidatedBuffer(
        retained_text=retained_text,
        retrievable_mask=retrievable_mask,
        total_tokens=cur,
        budget_enforcement=enforcement,
        notes=dict(mapped=int(sum(retrievable_mask))),
    )


def _smoke() -> int:
    memory = [
        Item(session_id=f"s{i}",
             text=("user: I went to Paris. assistant: Lovely. " * 2),
             n_tokens=40 + i * 5)
        for i in range(3)
    ]
    raw = sum(it.n_tokens for it in memory)
    cap = int(raw * 1.0)
    t0 = time.time()
    buf = consolidate(memory, budget_tokens=cap, llm_model="deepseek-v3.2")
    print(f"SimpleMem smoke kept={sum(buf.retrievable_mask)}/{len(memory)} "
          f"total={buf.total_tokens} enforce={buf.budget_enforcement} dt={time.time()-t0:.1f}s")
    return 0


if __name__ == "__main__":
    raise SystemExit(_smoke())
